version: '3.8'
services:
  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src/Introduction:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
